# .github/workflows/clean_bucket.yml  (main branch)
name: Enable Clean GCS Bucket
on: workflow_dispatch
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Placeholder to register workflow"
